name: Build & Deploy to DEV
on:
  pull_request:
    types: [opened, reopened,edited,synchronize]
    branches:   
      - 'devbranch'


jobs:
   build:
    runs-on: ubuntu-latest    
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    environment: dev
    env:
      DOCKER_IMAGE_TAG: ${{ github.sha}}
      DOCKER_CONTEXT: rsbc-ride-producer-api/src
      DOCKER_IMAGE_NAME: rbe5-images/ride-producer-api
      DOCKER_FILE: src/Dockerfile.multistage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate and set context for dev get cluster ca
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
          openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER_DEV }}
          namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-dev"
      - name: Get Cluster ca secret for build
        run: |
          oc get secret ${{ secrets.CLUSTER_CA_SECRET_NAME }} -o jsonpath='{.data.ca\.p12}' | base64 -d -i > src/certs/ca.p12
          pwd
          ls src

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKER_CONTEXT }}
          file: ${{ env.DOCKER_FILE }}
          push: false
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

  
        